### ISSUE TITLE
How to run the experiments based on the .yaml configuration and reproduce the figures in the paper?

### ISSUE THREAD

**Issue by wuyujack** [RobertCsordas/modules#1]
Hi, great thanks for sharing your code for replication! I came across some questions about starting the experiments and reproduction:

- What command should I use for starting an experiment based on a specific `.yaml` file in folder `sweeps`? It seems like you only summarize the steps we should do in the README instead of giving details command to run them.

- Should I first finish all the experiments based on all the `.yaml` in folder `sweeps` then run the `run_all.sh` in folder `paper` to reproduce the figures in your papers?

- When I try to run the `run_all.sh` in the folder `paper`, after I specified the `configs` for my wandb project, I get the error that the `edges = response.get("project", {}).get("sweeps", {}).get("edges")` return empty list. I noticed that you are not required for installing the `gql` in the `requrements.txt`. After installing it, I still get an empty response. Any idea to fix it?

**Comment by RobertCsordas** [comment]
Dear Jason,

Sorry, I did not notice your issue until now.

- Running the sweeps is cluster-specific, that's the reason it is not included in the README. You can find more information on W&B website: https://docs.wandb.com/sweeps/quickstart. You should run ```wandb sweep sweeps/<yaml_file>``` in the root directory of the project. You should run that on each node of your cluster. To make this easier, I use the following tool: https://github.com/robertcsordas/cluster_tool.

- Yes, if you want to run the run_all.sh. If you just want to reproduce a specific plot, you can check in the python file which experiments it loads, and just run the specific yaml files.

- The error is probably because you didn't run any sweeps. However that part of the code is based on reverse-engineering the W&B website, so one might run into unexpected issues. I just checked it and it still works for me currently, so they did not change the API. I added the gql to requirements, thanks for noticing!

Let me know if you run into further issues.
